# Generated by Django 4.0.6 on 2022-08-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagas',
            name='escolaridade',
            field=models.CharField(choices=[('A', 'Ensino Fundamental'), ('B', 'Ensino médio'), ('C', 'Tecnólogo'), ('D', 'Ensino Superior'), ('E', 'Pós/MBA/Mestrado'), ('F', 'Doutorado')], max_length=1),
        ),
        migrations.AlterField(
            model_name='vagas',
            name='faixa_salarial',
            field=models.CharField(choices=[('a', 'Até 1.000'), ('b', 'De 1.000 a 2.000'), ('c', 'De 2.000 a 3.000'), ('d', 'Acima de 3.000')], max_length=1),
        ),
    ]
