# Generated by Django 4.0.6 on 2022-08-12 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_empresa', '0002_alter_vagas_escolaridade_alter_vagas_faixa_salarial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faixa_salarial', models.CharField(choices=[('a', 'Até 1.000'), ('b', 'De 1.000 a 2.000'), ('c', 'De 2.000 a 3.000'), ('d', 'Acima de 3.000')], max_length=1)),
                ('experiencia', models.TextField()),
                ('escolaridade', models.CharField(choices=[('A', 'Ensino Fundamental'), ('B', 'Ensino médio'), ('C', 'Tecnólogo'), ('D', 'Ensino Superior'), ('E', 'Pós/MBA/Mestrado'), ('F', 'Doutorado')], max_length=1)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_empresa.vagas')),
            ],
        ),
    ]
